### ISSUE TITLE
Migrations not done for test environment with --env or -e option Win10

### ISSUE THREAD

**Issue by victorolweny** [db-migrate/pg#20]
I have installed `db-migrate` and `db-migrate-pg` driver all locally and run it with script hook in `package.json`

```
"scripts": {
    "migrate": "node node_modules/db-migrate/bin/db-migrate"
```
In my `database.json` file I have described environments for `dev` and `test` as shown below
```
{
  "dev": {
    "driver": "pg",
    "user": {"ENV": "PGUSER"},
    "password": {"ENV": "PGPASSWORD"},
    "host": {"ENV": "PGHOST"},
    "database": {"ENV": "PGDATABASE"}
  },
  "test": {
    "driver": "pg",
    "user": "myusername",
    "password": "mypwd",
    "host": "localhost",
    "database": "test"
  }
```
Also am using [dotenv](https://www.npmjs.com/package/dotenv) and that is where the envs for dev are picked up.

I can run migrations on the dev database successfully `yarn run migrate up`

But when I change the environment with the --env option or -e  option with test, it runs the migrations on the dev environment which of course will return no migrations to run

```
>yarn run migrate up --env test
yarn run v0.27.5
$ node node_modules/db-migrate/bin/db-migrate "up"
[INFO] No migrations to run
[INFO] Done
Done in 0.90s.
```

I dont know what the issue is?

**Comment by wzrdtales** [comment]
Hey @victorolweny,

unfortunately we can't help you if you don't provide us all informations necessary to reproduce your case.

This means, **always** post:
- used node version
- used npm version
- used db-migrate version
- used driver and its version
- used plugins
- full output of the verbose run
- in complex cases a full gist, as an executable proof
- if necessary used migrations and configuration details (**replace sensible informations before posting configs!**)
- if necessary code samples

As soon as you provide us all information needed, we have an easy way to reproduce your problem and provide you with the help or bugfix you need.

Thank you.

**Comment by victorolweny** [comment]
Node version `v6.11.1`
Npm version `3.10.10`
Yarn version `v0.27.5`

packages.json dependencies
```
"dependencies": {
    "body-parser": "^1.17.2",
    "compression": "^1.7.0",
    "db-migrate": "^0.10.0-beta.21",
    "db-migrate-pg": "0.2.4",
    "dotenv": "^4.0.0",
    "express": "^4.15.3",
    "helmet": "^3.8.0",
    "pg": "^7.0.2"
  },
  "devDependencies": {
    "chai": "^4.1.0",
    "mocha": "^3.4.2",
    "morgan": "^1.8.2",
    "sinon": "^2.4.1"
  }
```
Running the migrations
```

database.json
```
{
  "dev": {
    "driver": "pg",
    "user": {"ENV": "PGUSER"},
    "password": {"ENV": "PGPASSWORD"},
    "host": {"ENV": "PGHOST"},
    "database": {"ENV": "PGDATABASE"}
  },
  "test": {
    "driver": "pg",
    "user": "myusernamehere",
    "password": "mypwdhere",
    "host": "localhost",
    "database": "test"
  },
  "sql-file" : true
}
```
And finally the .env has this only
```
PGUSER=<myusername>
PGHOST='localhost'
PGPASSWORD= <mypwd>
PGDATABASE=<database name different from one in test in database.json>
PGPORT=5432
```
>yarn run migrate up
yarn run v0.27.5
$ node node_modules/db-migrate/bin/db-migrate "up"
received data: /* Replace with your SQL commands */

CREATE OR REPLACE FUNCTION ....
CREATE TABLE IF NOT EXISTS  
....

[INFO] Processed migration ....
[INFO] Done
Done in 1.05s.
```
Running migrations for test
```
>yarn run migrate up --env test
yarn run v0.27.5
$ node node_modules/db-migrate/bin/db-migrate "up"
[INFO] No migrations to run
[INFO] Done
Done in 0.81s.
```

**Comment by wzrdtales** [comment]
Thanks for this @victorolweny, but still missing on the verbose run, so too less information.

**Comment by victorolweny** [comment]
```
>yarn run migrate up --verbose
yarn run v0.27.5
verbose 0.813 Checking for configuration file "E:\\..\\.n
pmrc".
verbose 0.816 Checking for configuration file "C:\\...\\.npmrc".
verbose 0.817 Found configuration file "C:\\...\\.npmrc".
verbose 0.818 Checking for configuration file "E:\\...\\.npmrc".
verbose 0.819 Checking for configuration file "E:\\...\\.n
pmrc".
verbose 0.82 Checking for configuration file "E:\\...\\.npmrc".
verbose 0.821 Checking for configuration file "E:\\..\\.npmrc".
verbose 0.824 Checking for configuration file "E:\\...\\.y
arnrc".
verbose 0.824 Checking for configuration file "C:\\...\\.yarnrc".
verbose 0.825 Found configuration file "C:\\...\\.yarnrc".
verbose 0.825 Checking for configuration file "E:\\...\\nodejs\\.yarnrc".
verbose 0.826 Checking for configuration file "E:\\...\\.y
arnrc".
verbose 0.826 Checking for configuration file "E:\\...\\.yarnrc".
verbose 0.827 Checking for configuration file "E:\\...\\.yarnrc".
verbose 0.831 current time: 2017-08-01T12:18:35.582Z
$ node node_modules/db-migrate/bin/db-migrate "up"
received data: /* Replace with your SQL commands */

CREATE OR REPLACE FUNCTION ....
CREATE TABLE IF NOT EXISTS 
....
[INFO] Processed migration ....
[INFO] Done
Done in 1.10s.
```

```
>yarn run migrate up --verbose --env test
yarn run v0.27.5
verbose 0.786 Checking for configuration file "E:\\...\\.n
pmrc".
verbose 0.793 Checking for configuration file "C:\\...\\.npmrc".
verbose 0.798 Found configuration file "C:\\...\\.npmrc".
verbose 0.799 Checking for configuration file "E:\\...\\.npmrc".
verbose 0.799 Checking for configuration file "E:\\...\\.n
pmrc".
verbose 0.8 Checking for configuration file "E:\\...\\.npmrc".
verbose 0.8 Checking for configuration file "E:\\...\\.npmrc".
verbose 0.805 Checking for configuration file "E:\\...\\.y
arnrc".
verbose 0.807 Checking for configuration file "C:\\...\\.yarnrc".
verbose 0.807 Found configuration file "C:\\...\\.yarnrc".
verbose 0.808 Checking for configuration file "E:\\...\\.yarnrc".
verbose 0.809 Checking for configuration file "E:\\...\\.y
arnrc".
verbose 0.809 Checking for configuration file "E:\\...\\.yarnrc".
verbose 0.81 Checking for configuration file "E:\\...\\.yarnrc".
verbose 0.814 current time: 2017-08-01T12:23:10.705Z
$ node node_modules/db-migrate/bin/db-migrate "up"
[INFO] No migrations to run
[INFO] Done
Done in 1.08s.
```

**Comment by wzrdtales** [comment]
Ok so here we have the problem.

Not all arguments are passed to db-migrate. You need to stop using either npm scripts for this, or you need to place the whole command in there including the arguments.

Btw. for local installations you should install db-migrate just globally, for local environments where you want to run this command having a dedicated script for this might be a good idea anyway though. And you can also always find the bins in `node_modules/.bin/db-migrate` on local installs btw.

**Comment by victorolweny** [comment]
Okay. Did the global installation and go it working
Thanks

**Comment by wzrdtales** [comment]
You're welcome. Feel free to open any other issue, if needed.
