### ISSUE TITLE
Connector fails on server version 10.3

### ISSUE THREAD

**Issue by alessbelli** [db-migrate/pg#35]
It seems as though the "Server version check" with semver fails with my server which is Debian 10.3.1
Just by looking into the file where the error occurs (index -> line 172) I would say that the extra parsing of the os version does not take into account the fact that the os being 2-digit-long breaks the check, since, the sub-sub-version is not appended correctly and the 'semver.gte()' check fails. 

Am I right, has anyone encountered thi issue, and is there a fix?

**Comment by alessbelli** [comment]
Sorry for the hassle, looked a little deeper and newer versions had that solved. not sure if it's db-migrate 10.3 -> 11.1, db-migrate-pg 0.3-> 0.4 or the entire docker image I was using going from node 8.9 to 9.11, but I solved it by upgrading stuff.

**Comment by wzrdtales** [comment]
No worries, it was db-migrate-pg though since this is purely driver related :)
