### ISSUE TITLE
Uncaught exception if not possible to connect to databse

### ISSUE THREAD

**Issue by vlezhnin** [db-migrate/pg#7]
Let's assume that database is not available. When connect is called, then null error is returned.

```
exports.connect = function(config, intern, callback) {

    internals = intern;

    log = intern.mod.log;
    type = intern.mod.type;

    if (config.native) { pg = pg.native; }
    var db = config.db || new pg.Client(config);
    callback(null, new PgDriver(db, config.schema, intern));
};
```

After that init is called, inside which this code is executed.

```
init: function(connection, schema, intern) {
        this._escapeString = '\'';
        this._super(intern);
        this.internals = intern;
        this.connection = connection;
        this.schema = schema || "public";
        this.connection.connect();
    },
```

The last string `this.connection.connect();` in case of an connection refused error, will just hide it. Connect function can accept callback(err) as parameter, which, in my opinion, should be processed, and given back to the user.

Otherwise even in case of a connection error user gets a driver and will try to execute some queries, which will execute  'this.connection.query.apply(this.connection, params);' and cause an uncaught exception.
##

**Comment by wzrdtales** [comment]
Will probably change like it has a while ago for the mysql driver.
